# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_api_client.api.categories_api import CategoriesApi


class TestCategoriesApi(unittest.TestCase):
    """CategoriesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CategoriesApi()

    def tearDown(self) -> None:
        pass

    def test_create_category(self) -> None:
        """Test case for create_category

        Create a category
        """
        pass

    def test_create_category_link_for_node(self) -> None:
        """Test case for create_category_link_for_node

        Assign a node to a category
        """
        pass

    def test_delete_category(self) -> None:
        """Test case for delete_category

        Delete a category
        """
        pass

    def test_delete_category_link_from_node(self) -> None:
        """Test case for delete_category_link_from_node

        Unassign a node from a category
        """
        pass

    def test_get_category(self) -> None:
        """Test case for get_category

        Get a category
        """
        pass

    def test_list_categories_for_node(self) -> None:
        """Test case for list_categories_for_node

        List categories that a node is assigned to
        """
        pass

    def test_list_subcategories(self) -> None:
        """Test case for list_subcategories

        List categories
        """
        pass

    def test_update_category(self) -> None:
        """Test case for update_category

        Update a category
        """
        pass


if __name__ == '__main__':
    unittest.main()
