# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_core_api_client.models.model_property import ModelProperty

class TestModelProperty(unittest.TestCase):
    """ModelProperty unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ModelProperty:
        """Test ModelProperty
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ModelProperty`
        """
        model = ModelProperty()
        if include_optional:
            return ModelProperty(
                id = '',
                title = '',
                description = '',
                default_value = '',
                data_type = '',
                is_multi_valued = True,
                is_mandatory = True,
                is_mandatory_enforced = True,
                is_protected = True,
                constraints = [
                    alfresco_core_api_client.models.constraint.Constraint(
                        id = '', 
                        type = '', 
                        title = '', 
                        description = '', 
                        parameters = {
                            'key' : None
                            }, )
                    ]
            )
        else:
            return ModelProperty(
                id = '',
        )
        """

    def testModelProperty(self):
        """Test ModelProperty"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
