# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_core_api_client.models.rating import Rating

class TestRating(unittest.TestCase):
    """Rating unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Rating:
        """Test Rating
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Rating`
        """
        model = Rating()
        if include_optional:
            return Rating(
                id = '',
                aggregate = alfresco_core_api_client.models.rating_aggregate.Rating_aggregate(
                    number_of_ratings = 56, 
                    average = 56, ),
                rated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                my_rating = ''
            )
        else:
            return Rating(
                id = '',
                aggregate = alfresco_core_api_client.models.rating_aggregate.Rating_aggregate(
                    number_of_ratings = 56, 
                    average = 56, ),
        )
        """

    def testRating(self):
        """Test Rating"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
