# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from alfresco_core_api_client.api.storage_info_api import StorageInfoApi


class TestStorageInfoApi(unittest.TestCase):
    """StorageInfoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StorageInfoApi()

    def tearDown(self) -> None:
        pass

    def test_get_storage_properties(self) -> None:
        """Test case for get_storage_properties

        Retrieve storage properties for given content
        """
        pass

    def test_get_version_storage_properties(self) -> None:
        """Test case for get_version_storage_properties

        Retrieve storage properties for given version content
        """
        pass

    def test_request_archive_content(self) -> None:
        """Test case for request_archive_content

        Request to send given content to archive
        """
        pass

    def test_request_archive_version_content(self) -> None:
        """Test case for request_archive_version_content

        Request to send given version content to archive
        """
        pass

    def test_request_restore_content_from_archive(self) -> None:
        """Test case for request_restore_content_from_archive

        Request to restore given content from archive
        """
        pass

    def test_request_restore_version_content_from_archive(self) -> None:
        """Test case for request_restore_version_content_from_archive

        Request to restore given version content from archive
        """
        pass


if __name__ == '__main__':
    unittest.main()
