# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from alfresco_core_api_client.models.tag_paging import TagPaging

class TestTagPaging(unittest.TestCase):
    """TagPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TagPaging:
        """Test TagPaging
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TagPaging`
        """
        model = TagPaging()
        if include_optional:
            return TagPaging(
                list = alfresco_core_api_client.models.tag_paging_list.TagPaging_list(
                    pagination = alfresco_core_api_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        total_items = 56, 
                        skip_count = 56, 
                        max_items = 56, ), 
                    entries = [
                        alfresco_core_api_client.models.tag_entry.TagEntry(
                            entry = alfresco_core_api_client.models.tag.Tag(
                                id = '', 
                                tag = '', 
                                count = 1.337, ), )
                        ], )
            )
        else:
            return TagPaging(
                list = alfresco_core_api_client.models.tag_paging_list.TagPaging_list(
                    pagination = alfresco_core_api_client.models.pagination.Pagination(
                        count = 56, 
                        has_more_items = True, 
                        total_items = 56, 
                        skip_count = 56, 
                        max_items = 56, ), 
                    entries = [
                        alfresco_core_api_client.models.tag_entry.TagEntry(
                            entry = alfresco_core_api_client.models.tag.Tag(
                                id = '', 
                                tag = '', 
                                count = 1.337, ), )
                        ], ),
        )
        """

    def testTagPaging(self):
        """Test TagPaging"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
