# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional, Union
from pydantic import BaseModel, StrictBool, StrictFloat, StrictInt, StrictStr
from pydantic import Field
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Category(BaseModel):
    """
    Category
    """ # noqa: E501
    id: StrictStr = Field(description="The identifier for the category.")
    name: StrictStr = Field(description="The name of the category.  This must be unique within the parent category. ")
    parent_id: Optional[StrictStr] = Field(default=None, description="The id of the parent category (or -root- if this is a top level category).", alias="parentId")
    has_children: Optional[StrictBool] = Field(default=None, description="True if the category has at least one child category.", alias="hasChildren")
    count: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="The number of nodes that are assigned to this category.")
    path: Optional[StrictStr] = Field(default=None, description="The path to this category.")
    __properties: ClassVar[List[str]] = ["id", "name", "parentId", "hasChildren", "count", "path"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Category from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Category from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "parentId": obj.get("parentId"),
            "hasChildren": obj.get("hasChildren"),
            "count": obj.get("count"),
            "path": obj.get("path")
        })
        return _obj


