# coding: utf-8

"""
    Alfresco Content Services REST API

    **Core API**  Provides access to the core features of Alfresco Content Services. 

    The version of the OpenAPI document: 1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictBool, StrictStr, field_validator
from pydantic import Field
from alfresco_core_api_client.models.network_quota import NetworkQuota
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class PersonNetwork(BaseModel):
    """
    A network is the group of users and sites that belong to an organization. Networks are organized by email domain. When a user signs up for an Alfresco account , their email domain becomes their Home Network. 
    """ # noqa: E501
    id: StrictStr = Field(description="This network's unique id")
    home_network: Optional[StrictBool] = Field(default=None, description="Is this the home network?", alias="homeNetwork")
    is_enabled: StrictBool = Field(alias="isEnabled")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    paid_network: Optional[StrictBool] = Field(default=None, alias="paidNetwork")
    subscription_level: Optional[StrictStr] = Field(default=None, alias="subscriptionLevel")
    quotas: Optional[List[NetworkQuota]] = None
    __properties: ClassVar[List[str]] = ["id", "homeNetwork", "isEnabled", "createdAt", "paidNetwork", "subscriptionLevel", "quotas"]

    @field_validator('subscription_level')
    def subscription_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('Free', 'Standard', 'Enterprise'):
            raise ValueError("must be one of enum values ('Free', 'Standard', 'Enterprise')")
        return value

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PersonNetwork from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in quotas (list)
        _items = []
        if self.quotas:
            for _item in self.quotas:
                if _item:
                    _items.append(_item.to_dict())
            _dict['quotas'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of PersonNetwork from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "homeNetwork": obj.get("homeNetwork"),
            "isEnabled": obj.get("isEnabled"),
            "createdAt": obj.get("createdAt"),
            "paidNetwork": obj.get("paidNetwork"),
            "subscriptionLevel": obj.get("subscriptionLevel"),
            "quotas": [NetworkQuota.from_dict(_item) for _item in obj.get("quotas")] if obj.get("quotas") is not None else None
        })
        return _obj


